@echo off
color 0a
cls

echo ********************************
echo ********************************
echo ******** The Matrix v1 *********
echo ******** By: jtrent238 *********
echo ********************************
echo ********************************
pause

:XXX
color 0b
echo X
color 0c
echo  X
color 0d
echo   X
color 0e
echo    X
color 0f
echo     X
color 01
echo      X
color 02
echo       X
color 03
echo        X
color 04
echo         X
color 05
echo          X
color 06
echo           X
color 07
echo            X
color 08
echo             X
color 0a
echo              X
color 0b
echo               X
color 0c
echo                X
color 0d
echo                 X
color 0e
echo                  X
color 0f
echo                   X
color 01
echo                    X
color 02
echo                     X
color 03
echo                      X
color 04
echo                       X
color 05
echo                        X
color 06
echo                         X
color 07
echo                          X
color 08
echo                           X
color 0a
echo                            X
color 0b
echo                             X
color 0c
echo                            X
color 0d
echo                           X
color 0e
echo                          X
color 0f
echo                         X
color 01
echo                        X
color 02
echo                       X
color 03
echo                      X
color 04
echo                     X
color 05
echo                    X
color 06
echo                   X
color 07
echo                  X
color 08
echo                 X
color 0a
echo                X
color 0b
echo               X
color 0c
echo              X
color 0d
echo             X
color 0e
echo            X
color 0f
echo           X
color 01
echo          X
color 02
echo         X
color 03
echo        X
color 04
echo       X
color 05
echo      X
color 06
echo     X
color 07
echo    X
color 08
echo   X
color 0a
echo  X
color 0b
goto XXX
